feat: prevent upgrades

diff --git a/kura/distrib/src/main/resources/docker-x86_64-nn/deb/control/prerm b/kura/distrib/src/main/resources/docker-x86_64-nn/deb/control/prerm
--- a/kura/distrib/src/main/resources/docker-x86_64-nn/deb/control/prerm
+++ b/kura/distrib/src/main/resources/docker-x86_64-nn/deb/control/prerm
@@ -1,4 +1,16 @@
 #!/bin/bash
+#
+# Copyright (c) 2023, 2025 Eurotech and/or its affiliates and others
+#
+# This program and the accompanying materials are made
+# available under the terms of the Eclipse Public License 2.0
+# which is available at https://www.eclipse.org/legal/epl-2.0/
+#
+# SPDX-License-Identifier: EPL-2.0
+#
+# Contributors:
+#  Eurotech
+#
 
 INSTALL_DIR=/opt/eclipse
 WD_TMP_FILE=/tmp/watchdog
@@ -95,6 +107,14 @@ function preRemove {
 ##############################################
 # PRE-REMOVE SCRIPT
 ##############################################
+
+# Fail if the first argument is 'upgrade' or 'failed-upgrade'
+if [ "$1" == "upgrade" ] || [ "$1" == "failed-upgrade" ]; then
+    echo "This package cannot be upgraded. Please uninstall the existing version before installing a new one."
+    exit 1
+fi
+
+
 echo ""
 echo "Uninstalling KURA..."
 
