feat: prevent upgrades (#5843)
* feat: prevent upgrades

* fix: correctly handle dpkg state machine

* feat: add suggestion about apt-mark hold and improved log

diff --git a/kura/distrib/src/main/resources/aarch64/deb/control/prerm b/kura/distrib/src/main/resources/aarch64/deb/control/prerm
--- a/kura/distrib/src/main/resources/aarch64/deb/control/prerm
+++ b/kura/distrib/src/main/resources/aarch64/deb/control/prerm
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (c) 2023, 2024 Eurotech and/or its affiliates and others
+# Copyright (c) 2023, 2025 Eurotech and/or its affiliates and others
 #
 # This program and the accompanying materials are made
 # available under the terms of the Eclipse Public License 2.0
@@ -140,6 +140,28 @@ function preRemove {
 ##############################################
 # PRE-REMOVE SCRIPT
 ##############################################
+
+# Fail if the first argument is 'upgrade' or 'failed-upgrade'
+if [ "$1" == "upgrade" ]; then
+    echo ""
+    echo "#####################################################################"
+    echo "#                                                                   #"
+    echo "#  ERROR: KURA upgrade is NOT supported!                            #"
+    echo "#  Please uninstall the existing version before upgrading.          #"
+    echo "#                                                                   #"
+    echo "#  To prevent accidental upgrades, you can hold this package with:  #"
+    echo "#      sudo apt-mark hold kura                                      #"
+    echo "#                                                                   #"
+    echo "#####################################################################"
+    echo ""
+    exit 1
+fi
+
+if [ "$1" == "failed-upgrade" ]; then
+    echo "This package cannot be upgraded. Please uninstall the existing version before installing a new one."
+    exit 1
+fi
+
 echo ""
 echo "Uninstalling KURA..."
 
